#ifndef MCUJS_RUNTIME_VALIDATION_BACKEND_STUBS_H
#define MCUJS_RUNTIME_VALIDATION_BACKEND_STUBS_H

#include <stdbool.h>
#include <stddef.h>

extern int mcujs_test_i2c_result;
extern unsigned mcujs_test_i2c_write_calls;
extern unsigned mcujs_test_i2c_read_calls;
extern size_t mcujs_test_i2c_last_length;
extern unsigned mcujs_test_adc_read_calls;
extern unsigned mcujs_test_adc_calibrated_calls;
extern int mcujs_test_adc_raw_value;
bool mcujs_test_gpio_is_output(unsigned pin);
int mcujs_test_gpio_level_at(unsigned pin);
int mcujs_test_gpio_pull_at(unsigned pin);
#if defined(MCUJS_PLATFORM_RP2)
extern unsigned mcujs_test_gpio_init_calls;
extern int mcujs_test_i2c_init_result;
extern unsigned mcujs_test_i2c_init_calls;
extern unsigned mcujs_test_pwm_config_calls;
extern unsigned mcujs_test_pwm_divider_scaled;
extern unsigned mcujs_test_pwm_wrap;
extern unsigned mcujs_test_pwm_duty_calls;
extern unsigned mcujs_test_pwm_level;
extern unsigned mcujs_test_pwm_enable_calls;
extern unsigned mcujs_test_pwm_disable_calls;
extern int mcujs_test_spi_init_result;
extern unsigned mcujs_test_spi_init_calls;
extern unsigned mcujs_test_spi_deinit_calls;
extern unsigned mcujs_test_adc_gpio_init_calls;
extern unsigned mcujs_test_adc_last_pin;
extern unsigned mcujs_test_adc_init_calls;
extern unsigned mcujs_test_adc_select_calls;
extern bool mcujs_test_pio_can_add_program;
extern unsigned mcujs_test_neopixel_init_calls;
extern unsigned mcujs_test_neopixel_last_pin;
extern unsigned mcujs_test_neopixel_write_calls;
extern unsigned mcujs_test_neopixel_last_word;
extern int mcujs_test_dma_claim_result;
extern unsigned mcujs_test_dma_claim_calls;
extern bool mcujs_test_dma_claim_required;
extern unsigned mcujs_test_dma_configure_calls;
extern size_t mcujs_test_dma_last_length;
#endif
#if defined(MCUJS_PLATFORM_ESP32)
extern int mcujs_test_gpio_result;
extern unsigned mcujs_test_i2c_param_config_calls;
extern unsigned mcujs_test_i2c_driver_install_calls;
extern unsigned mcujs_test_i2c_driver_delete_calls;
extern int mcujs_test_ledc_result;
extern unsigned mcujs_test_ledc_resolution;
extern unsigned mcujs_test_ledc_configured_resolution;
extern unsigned mcujs_test_ledc_actual_frequency;
extern unsigned mcujs_test_ledc_stop_calls;
extern unsigned mcujs_test_gpio_reset_calls;
extern unsigned mcujs_test_gpio_direction_calls;
extern unsigned mcujs_test_gpio_pull_calls;
extern unsigned mcujs_test_gpio_level_calls;
extern unsigned mcujs_test_ledc_duty_calls;
extern unsigned mcujs_test_ledc_duty;
extern int mcujs_test_ledc_timer_result;
extern int mcujs_test_ledc_timer_deconfigure_result;
extern int mcujs_test_ledc_channel_result;
extern int mcujs_test_ledc_stop_result;
extern int mcujs_test_ledc_pause_result;
extern int mcujs_test_gpio_reset_result;
extern unsigned mcujs_test_ledc_timer_config_calls;
extern unsigned mcujs_test_ledc_timer_deconfigure_calls;
extern unsigned mcujs_test_ledc_timer_pause_calls;
extern unsigned mcujs_test_ledc_channel_config_calls;
extern int mcujs_test_adc_unit_result;
extern int mcujs_test_adc_config_result;
extern int mcujs_test_adc_read_result;
extern int mcujs_test_adc_calibration_result;
extern int mcujs_test_adc_millivolts;
extern int mcujs_test_temperature_install_result;
extern int mcujs_test_temperature_enable_result;
extern int mcujs_test_temperature_read_result;
extern int mcujs_test_temperature_disable_result;
extern float mcujs_test_temperature_celsius;
#endif

void mcujs_test_reset_backend(void);

#endif
