#define MCUJS_SD_SPI_BUS 2
#define MCUJS_SD_SCK_PIN 13
#define MCUJS_SD_MOSI_PIN 14
#define MCUJS_SD_MISO_PIN 12
#define MCUJS_SD_CS_PIN 8
#define MCUJS_SD_SPI_BAUD_HZ 4000000
#ifndef MCUJS_SD_READONLY
#define MCUJS_SD_READONLY 1
#endif
#define MCUJS_SD_POWER_PIN 10
#define MCUJS_SD_POWER_ACTIVE_HIGH 1
#define MCUJS_SD_CARD_DETECT_PIN -1
#define MCUJS_SD_SHARED_CS_PIN 15
